const cities = [
    "Vilnius",
    "Kaunas",
    "Klaipėda",
    "Šiauliai",
    "Panevežys",
    "Alytus",
    "Marijampolė",
    "Mažeikiai",
    "Jonava",
    "Utena",
    "Neringa",
    "Pagėgiai",
    "Palanga",
    "Kalvarija",
    "Rietavas",
    "Birštonas",
    "Druskininkai",
    "Kazlų Rūda",
    "Elektrėnai",
    "Visaginas",
    "Akmenės Rajonas",
    "Alytaus Rajonas",
    "Anykščių Rajonas",
    "Biržų Rajonas",
    "Ignalinos Rajonas",
    "Jonavos Rajonas",
    "Joniškio Rajonas",
    "Jurbarko Rajonas",
    "Kaišiadorių Rajonas",
    "Kauno Rajonas",
    "Kėdainių Rajonas",
    "Kelmės Rajonas",
    "Klaipėdos Rajonas",
    "Kretingos Rajonas",
    "Kupiškio Rajonas",
    "Lazdijų Rajonas",
    "Pakruojo Rajonas",
    "Mažeikių Rajonas",
    "Molėtų Rajonas",
    "Panevėžio Rajonas",
    "Pasvalio Rajonas",
    "Plungės Rajonas",
    "Prienų Rajonas",
    "Radviliškio Rajonas",
    "Raseinių Rajonas",
    "Rokiškio Rajonas",
    "Skuodo Rajonas",
    "Šakių Rajonas",
    "Šalčininkų Rajonas",
    "Šiaulių Rajonas",
    "Šilalės Rajonas",
    "Šilutės Rajonas",
    "Širvintų Rajonas",
    "Švenčionių Rajonas",
    "Tauragės Rajonas",
    "Telšių Rajonas",
    "Trakų Rajonas",
    "Ukmergės Rajonas",
    "Utenos Rajonas",
    "Varėnos Rajonas",
    "Vilkaviškio Rajonas",
    "Vilniaus Rajonas",
    "Zarasų Rajonas"
  ];
 export default cities;  